added company name after logo image and hover effect in nav-links
tamalCodes/Milan pull request #767
Opened 2023-05-27 05:42 UTC by Iamdivyak

feat:  added company name after the logo and hover effect in nav-links

### Related Issue 

Closes: #744

#### Changes made 👷🏻‍♂️
1. name after logo image
2. By hovering in any nav-links. we will get a red line appear bottom to the nav-link with a beautiful transition effect

#### Screenshots  📸

![Screenshot (24)](https://github.com/IAmTamal/Milan/assets/102896170/ee4c9ea4-7c9e-4d63-8379-92728646e8e8)

2023-05-28 05:22 UTC, IAmTamal requested changes
Also for the parent anchor tag that includes the Image and span - can we perhaps use `Link` there ?  We might also wanna add a flex based display because the image and the brand-name looks not aligned.

```css
    display: flex;
    align-items: center;
```
This can be added to the parent div in order to keep the image and brand-name in sync.

2023-05-28 05:22 UTC, IAmTamal commented on src/styles/Navbar.css
> +  font-size: 2.1rem;
Can we the change it to `font-size: 1.5rem;` ?

2023-05-28 05:22 UTC, IAmTamal commented on src/styles/Navbar.css
> +.nav-item a::before{
I think we can remove this hover state because someone is working on it on #734 , and your issue was primarily to add the name besides.

2023-05-28 13:52 UTC, Iamdivyak commented
made required changes

2023-05-28 15:23 UTC, IAmTamal requested changes
The reason we are changing the class names is to make sure we stay consistent across the styling and naming part !

The rest of the changes look fantastic.

2023-05-28 15:23 UTC, IAmTamal commented on src/components/Navbar.jsx
> +          <Link className="Link" to={"/"}>
Instead of the class name being `Link` can we make it something relevant? 
How about `nav_brand_parent`

2023-05-28 15:23 UTC, IAmTamal commented on src/components/Navbar.jsx
> +            /> <span className="brand-name">MILAN</span>
And for this one, the classname can be `nav_brand_name`

2023-05-28 15:23 UTC, IAmTamal commented on src/components/Navbar.jsx
>                className="nav_bramhin_img"
And we can change the image's class name as `nav_brand_img`

2023-05-28 16:50 UTC, Iamdivyak commented
done

2023-05-29 16:40 UTC, tamalCodes approved these changes
**Amazing work,**
This looks good to me, will be merged soon 🎉.

2023-05-29 16:41 UTC, merged