feat: grammatical and spelling errors were resolved
tamalCodes/Milan pull request #818
Opened 2023-06-06 06:23 UTC by HimanshuNarware

feat:  grammatical and spelling errors were resolved from the website, It will improve the readability of the website as well as improve the user experience

### Related Issue 

Closes: #
#772

#### Changes made 👷🏻‍♂️
resolved all grammatical and spelling errors present on the website and other files

2023-06-07 04:13 UTC, tamalCodes commented on public/CODE_OF_CONDUCT.md
Hi there, please donot make any changes to this file, as we are working on it.

2023-06-07 04:21 UTC, tamalCodes requested changes
With the following changes done, we can get this merge. Please always checkout for duplicates, and unwanted spaces.

2023-06-07 04:21 UTC, tamalCodes commented on rules/FrontendSetup.md
Hi there, why is `# Frontend Setup` done 2 times and why is the whole thing copied and pasted again ? 
The goal was to change particular words that might have been grammatically incorrect but here the whole thing was just copied and pasted. Please remove this.

![image](https://github.com/tamalCodes/Milan/assets/72851613/e44d177e-02f4-4c45-917b-5fc5b9f13c31)

2023-06-07 04:21 UTC, tamalCodes commented on src/components/Events/index.jsx
> +        All our partnered NGOs, host various events be they educational,
Please change `they` back to `it` as both are grammatically correct.

2023-06-07 04:21 UTC, tamalCodes commented on src/components/Events/index.jsx
>          </p>
Remove the duplicate space after `more` and before `!!`

2023-06-07 04:21 UTC, tamalCodes commented on src/pages/Donate.jsx
> +            lives..
Remove this extra dot after `lives.`

2023-06-07 04:21 UTC, tamalCodes commented on src/pages/shops/ShopCategory.jsx
> +                charities, NGOs, and  orphanages. We don't take any profit from the
Remove this extra space after `and`

2023-06-07 05:29 UTC, HimanshuNarware commented on rules/FrontendSetup.md
sorry sir it's my mistake I resolve all the errors I have done in the code.

2023-06-07 05:43 UTC, tamalCodes commented on rules/FrontendSetup.md
> sorry sir it's my mistake I resolve all the errors I have done in the code.

Hi there, no need to call me sir - just Tamal is fine, I'm still in college. Mistakes are something we all make & learn. 
Don't worry.

2023-06-07 09:11 UTC, HimanshuNarware commented
I have made all changes in my code as you said, but what about the code of conduct you said that dont make any changes in this file

2023-06-09 03:46 UTC, tamalCodes commented
Hi @HimanshuNarware , yes we don't want any changes now to the Code of Conduct file which you added. It would be better to remove this .

![image](https://github.com/tamalCodes/Milan/assets/72851613/76a206f5-8545-4687-80b0-8016f48c6dcb)

2023-06-09 03:50 UTC, tamalCodes requested changes
The rest of the changes looks good to me, with the below mentioned changes done we can finally merge it !

2023-06-09 03:50 UTC, tamalCodes commented on public/CODE_OF_CONDUCT.md
Please do remove this file, as we are working on it - and we won't be having it inside `/public` directory. 
Thanks.

2023-06-09 06:50 UTC, HimanshuNarware commented on public/CODE_OF_CONDUCT.md
ok

2023-06-09 06:55 UTC, HimanshuNarware commented
CODE_OF_CONDUCT REMOVED

2023-06-09 20:55 UTC, merged