Login and Register page with validation errors
tamalCodes/Milan pull request #823
Opened 2023-06-07 05:14 UTC by Pushpendra33

### Related Issue 
issue number #735 

#### Changes made 👷🏻‍♂️
Improved login and register form with global compoents and validation (yup).
With this update, users will be able to access the application using their credentials, providing an additional layer of error throwing on the login and registration process.
With react-hook-form user have to pass all the validations to perform sign up or login.

### Packages installed by my side
1. @hookform/resolvers
2. react-hook-form
3. yup

#### Screenshots  📸
![Screenshot from 2023-06-05 12-20-07](https://github.com/tamalCodes/Milan/assets/108654034/dae70c3a-4162-4b43-804e-36f8a80b9f83)

2023-06-09 03:52 UTC, tamalCodes commented
Hi @Pushpendra33 , that's a lot of files to go through  and review properly - I will take it slowly, thanks for working so hard on it !

2023-06-09 05:14 UTC, Pushpendra33 commented
> Hi @Pushpendra33 , that's a lot of files to go through and review properly - I will take it slowly, thanks for working so hard on it !

Thanks for the appreciation @tamalCodes , take your time :+1: .

2023-06-10 14:32 UTC, tamalCodes requested changes
We also need some changes based on devices. 
For example to the left are the changes you made, and to the right is the original one.

![image](https://github.com/tamalCodes/Milan/assets/72851613/f3b8444e-aaee-4d44-9fec-03d20d9394ea)

2023-06-10 14:32 UTC, tamalCodes commented on src/pages/clubs/ClubsRegister.jsx
For Club's register, we are not adding validations ? I checked [here](https://milan-phhl7dm48-iamtamal.vercel.app/clubs/register) too, but did not find anything.

2023-06-14 10:19 UTC, Pushpendra33 commented
All the changes requested from your side are completed.
Please check and go through it

2023-06-17 16:32 UTC, tamalCodes commented
I am closing this PR as it was requested by @Pushpendra33. We will continue with #850

2023-06-17 16:32 UTC, closed without merging