feat: google authentication frontend
tamalCodes/Milan pull request #849
Opened 2023-06-13 21:34 UTC by Santosh7017

### Related Issue 

Closes: #835 

#### Changes made 👷🏻‍♂️

The present pull request incorporates modifications to the user login and page, encompassing the inclusion of a Google login button to facilitate user authentication through their Google account, ensuring a high level of convenience.

#### Screenshots  📸

https://github.com/tamalCodes/Milan/assets/73546536/8cbf4d98-e308-449b-bc50-1f5861650ae3

2023-06-14 03:47 UTC, tamalCodes requested changes

2023-06-14 03:47 UTC, tamalCodes commented on src/service/MilanApi.js
> +    });
Can you please remove this code : 
```javascript
    toast.error(error, {
      position: toast.POSITION.TOP_RIGHT,
    });
```

and instead, use our personalised [toasts](https://github.com/tamalCodes/Milan/blob/main/src/utils/showToast.js) in the format `showSuccessToast("Hello")` or `showErrorToast ("Hello")`

2023-06-14 03:47 UTC, tamalCodes commented on src/pages/user/UserLogin.jsx
I think the design can be further improved, you can take motivation from Dribble pages to get a clear look. 
[This](https://dribbble.com/shots/17564792-Log-in-page-Untitled-UI) can be a good example, or even  [this](https://dribbble.com/shots/18567125-Sign-up-page-Untitled-UI).

2023-06-14 03:47 UTC, tamalCodes commented on src/pages/user/UserRegister.jsx
I have a question regarding this too - If someone do not have an account in MongoDB and just logs in with Google - will that create an account in the Database too ?

2023-06-14 05:01 UTC, Santosh7017 commented on src/pages/user/UserRegister.jsx
Yes, If user register for the first time it will, then user's email, first name, last name and a random hash password will be saved in database, like this
<img width="767" alt="244096764-e48edda1-9fba-4db9-bb13-30312b76bbaa (1)" src="https://github.com/tamalCodes/Milan/assets/73546536/f74c4a1b-0eb0-4e11-9d9b-5fa3881b4887">

2023-06-14 10:17 UTC, tamalCodes commented on src/pages/user/UserRegister.jsx
Cool, so if i do not have an account and I try to `log in` with Google - My account will be created and then I will be technically auto-logged in. Makes sense. Then I guess the next time when I try to Log in with Google, I would be able to !

2023-06-14 11:06 UTC, Santosh7017 commented on src/pages/user/UserRegister.jsx
yes! once you go to register or login and if you already registered then it will simply make you login, or if registering for first time user will be created in database and logged in automatically

2023-06-22 18:36 UTC, Santosh7017 commented
Hey @tamalCodes  
just changed the button design please have a look 
<img width="960" alt="image" src="https://github.com/tamalCodes/Milan/assets/73546536/bba423c3-15ce-4016-ab8a-72fbebebffa8">

is it good or need any changes

2023-06-24 05:21 UTC, tamalCodes commented
Please resolve the conflicts.

2023-06-24 12:34 UTC, Santosh7017 commented
> Hey @tamalCodes just changed the button design please have a look <img alt="image" width="960" src="https://user-images.githubusercontent.com/73546536/248023998-bba423c3-15ce-4016-ab8a-72fbebebffa8.png">
> 
> is it good or need any changes

Is it looking nice or need to change button position

2023-06-26 04:50 UTC, tamalCodes commented
Yep looks good. Please push these changes ASAP.

2023-06-27 04:37 UTC, tamalCodes commented
Hi @Santosh7017 , when i was running it locally from port `http://127.0.0.1:5173/user/register` on clicking the google icon it takes me to `/user/undefined` which is the 404 page.

Also in the console/network it says:  `MilanApi.js:183     GET http://localhost:5000/auth/login/success net::ERR_FAILED 403 (Forbidden)` though the backend is running fine. 

How do I fix this ?

2023-06-27 06:24 UTC, Santosh7017 commented
Have you configured CLIENT ID and Key

2023-06-28 20:24 UTC, Santosh7017 commented
Hello @tamalCodes, I have created a new branch called "GoogleAuthentication" after resolving conflicts to ensure it does not interfere with or disrupt the main code.

2023-06-28 20:44 UTC, Santosh7017 commented
Here is a working video 
https://github.com/tamalCodes/Milan/assets/73546536/508f297d-68bf-4b36-af5c-6b202382dccf

2023-06-28 20:46 UTC, Santosh7017 commented
Here is a working video 
https://github.com/tamalCodes/Milan/assets/73546536/6f8d545e-6fd3-40d3-bfd7-e5ed4ed322a0

2023-07-05 04:22 UTC, tamalCodes commented
Hi @Santosh7017 , the changes you made looks good to me - please fix the conflicts.

2023-07-05 18:37 UTC, Santosh7017 commented
@tamalCodes resolved conflicts, please have a look

2023-07-07 15:07 UTC, Santosh7017 commented
The code has already undergone modifications.

2023-07-10 03:42 UTC, Santosh7017 commented
Hey @tamalCodes please review the new changes

2023-07-20 09:51 UTC, Santosh7017 commented
Hey @tamalCodes,

2023-07-22 15:17 UTC, tamalCodes approved these changes
I changed the base branch, i will do some more testing, a little bit of design changes and will then deploy it up to production.

### Amazing work !
**The changes look good to me and will be merged soon.**

Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

2023-07-22 15:18 UTC, merged