feat: search clubs and events based on location and places
tamalCodes/Milan pull request #852
Opened 2023-06-15 20:26 UTC by suzy-g38

feat:  added search feature based on your current location and states. You can either search for events near you or can check which state is having how many events.

### Related Issue 

Closes: #710

#### Changes made 👷🏻‍♂️

#### Screenshots  📸

https://github.com/tamalCodes/Milan/assets/62666287/9355e2ae-d42e-4997-90fc-5eacc1bb6357

2023-06-18 16:57 UTC, tamalCodes requested changes
Please take a look at these changes. I will also check out your fork and run these locally to check it out for myself. Also, I think we can work on the styling. 

For example, we can improve the styles by using our `<Button/>` component, so that the styles of the button stays consistent across the page.

2023-06-18 16:57 UTC, tamalCodes commented on src/service/MilanApi.js
> +    console.log(User);
Please remove this `console.log`.

2023-06-18 16:57 UTC, tamalCodes commented on src/pages/display/StatesData.js
Also why a lot of the states are commented ?

2023-06-18 16:57 UTC, tamalCodes commented on src/pages/display/ClubsPage.jsx
> +            <button
If possible also remove these inline styles and add this to a separate `.css` file.

2023-06-28 06:18 UTC, suzy-g38 commented
@tamalCodes all the changes that you asked for, I did them. Sorry for taking so long, everytime I made a push I found a new error, it took some real time to complete every detail. Hope, the changes you asked for are made in the right way and you like them. Thanks.

2023-07-05 04:15 UTC, tamalCodes commented on src/components/SingleClubEvent.jsx
> +
Hey @suzy-g38 , did you make these changes ? 
As these aren't marked `outdated` so I am just getting sure.

2023-07-05 04:20 UTC, tamalCodes commented
Hey @suzy-g38 , i see that you made a couple of changes I suggested, again a couple of changes that I suggested had not been done. So please always click `Resolve Conversation` for the changes that you made, and for the ones you did not we can obviously talk.

For example for these changes, I suggested something which you did not do, yet the file says `outdated` as changes were made to it. So to avoid such convo - please click `Resolve Conversation` for the changes that you made.
![image](https://github.com/tamalCodes/Milan/assets/72851613/24668c85-04b8-4559-87bb-34630e4371cf)

If you don't it'll be tough to keep track of and I might then need to close the PR.

2023-07-05 04:58 UTC, suzy-g38 commented
> Hey @suzy-g38 , i see that you made a couple of changes I suggested, again a couple of changes that I suggested had not been done. So please always click `Resolve Conversation` for the changes that you made, and for the ones you did not, we can obviously talk.
> 
> For example for these changes, I suggested something which you did not do, yet the file says `outdated` as changes were made to it. So to avoid such convo - please click `Resolve Conversation` for the changes that you made.
> 
> ![image](https://user-images.githubusercontent.com/72851613/251035589-24668c85-04b8-4559-87bb-34630e4371cf.png)
> 
> If you don't it'll be tough to keep track of and I might then need to close the PR.

Sorry I didn't know about this resolve conversation feature. I will keep that in mind for sure. And yes there are I guess two changes from event and club page where you suggested the changes and I missed it honestly.

2023-07-05 09:22 UTC, tamalCodes commented
No worries, no worries - just make sure you hit the button when you resolve a particular thing, given the size of this amazing feature.  Conficts and stuffs are bound to come and go, we can solve those later on.

2023-07-06 10:22 UTC, suzy-g38 commented on src/pages/display/ClubsPage.jsx
> +  };
I could not make the change you suggested as the above code is not updating the state properly if somebody does not share their location. I also tried other ways( keeping the style you suggested) but I could not fix it. Also as I am not very used to with the suggested style of code, though I tried in many ways, there is still a possibility that maybe you can find it and be able to maintain the pattern and if you find please let me know about that I will be happy learn that.

2023-07-07 03:44 UTC, tamalCodes requested changes

2023-07-07 03:44 UTC, tamalCodes commented on src/pages/display/ClubsPage.jsx
![image](https://github.com/tamalCodes/Milan/assets/72851613/485c0d05-730e-480f-8ef2-4797fa1fac05)

I think the buttons we have, consists of different inline styles, which i don't ythink will be needed. Plus they are looking totally different from our theme. So please do fix this.

2023-07-07 03:44 UTC, tamalCodes commented on src/pages/display/ClubsPage.jsx
![image](https://github.com/tamalCodes/Milan/assets/72851613/c84909c5-20e1-476b-99b2-ae2046ab6997)

Also see how's there's an uneven spacing below ?

2023-07-08 08:05 UTC, suzy-g38 commented on src/pages/display/ClubsPage.jsx
> ![image](https://user-images.githubusercontent.com/72851613/251629460-485c0d05-730e-480f-8ef2-4797fa1fac05.png)
> 
> I think the buttons we have, consists of different inline styles, which i don't ythink will be needed. Plus they are looking totally different from our theme. So please do fix this.

Actually, I tried to use that first, the buttons which are already present but they have a hover effect which is creating a problem when you want to select and then deselect the button. I will then give it another try and will let you know.

2023-07-12 06:57 UTC, suzy-g38 commented on src/pages/display/ClubsPage.jsx
@tamalCodes I have made the changes that you asked for...and removed the hover. Hope you like it.

2023-07-14 17:20 UTC, tamalCodes commented on src/pages/display/ClubsPage.jsx
![image](https://github.com/tamalCodes/Milan/assets/72851613/af1508ee-6903-4e76-adb3-c33ed65bb182)


and if for an instance there are no results, do show a message that there was nothing found.

2023-07-18 06:33 UTC, suzy-g38 commented on src/pages/display/ClubsPage.jsx
> Hi about the button part i think it needs some more love. The font family, the size it's all different. Take a look at the screenshot. Doesn't these 2 buttons looks out of place ?
> 
> Please do fix these.
> 
> ![image](https://user-images.githubusercontent.com/72851613/253635357-00637443-45ac-4973-8d15-fdb37324ced9.png)

actually, I tried that first but the buttons looked soo small, So I changed that and make it look like the home page buttons(the buttons at the centre of the home page, you will find these pair similar to the home page's button pair). And Sorry actually that the design you want I keep failing to deliver that...I am not the frontend person actually, trying this designing stuff in open source but my failure is well spotted ig. Anyway, I will try my best to make it look the way you want. Thanks.

2023-07-21 09:16 UTC, suzy-g38 commented on src/pages/display/ClubsPage.jsx
@tamalCodes I have made the changes. hope you like it.

![image](https://github.com/tamalCodes/Milan/assets/62666287/1a2011f7-f800-40e4-95ba-4effd1588729)

2023-07-21 14:17 UTC, tamalCodes approved these changes
### Amazing work !
**The changes look good to me and will be merged soon.**


Do follow [Tamal](https://github.com/tamalCodes) for more Opensource fun projects and don't forget to drop a star so that you get updated about our latest [releases](https://github.com/tamalCodes/Milan/releases) (we will tag you and mention your work) and also a [shoutout](https://www.linkedin.com/feed/update/urn:li:activity:7073574804519354368/) on social media (LinkedIn and Twitter) !

Happy Opensource 🚀.

2023-07-21 14:20 UTC, merged

2023-07-21 14:26 UTC, suzy-g38 commented
@tamalCodes labels?

2023-07-22 08:11 UTC, suzy-g38 commented
@tamalCodes labels for gssoc?